// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfJPc7SV-RPdJ8MzY2q3-cqYy6ivSaTs',
    appId: '1:45830351220:web:ff3bf1c4bba5e45550e421',
    messagingSenderId: '45830351220',
    projectId: 'account-management-4ce5a',
    authDomain: 'account-management-4ce5a.firebaseapp.com',
    storageBucket: 'account-management-4ce5a.firebasestorage.app',
    measurementId: 'G-QL69H3L7T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1H5V7384c3v94SzQ4yPznWk0qfbw5S3c',
    appId: '1:45830351220:android:57ced7822f5d8e2a50e421',
    messagingSenderId: '45830351220',
    projectId: 'account-management-4ce5a',
    storageBucket: 'account-management-4ce5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5AXW0RUDHkRmlCY59K9-5XxRzLkGbLvE',
    appId: '1:45830351220:ios:098d8d63cf2353b150e421',
    messagingSenderId: '45830351220',
    projectId: 'account-management-4ce5a',
    storageBucket: 'account-management-4ce5a.firebasestorage.app',
    iosBundleId: 'com.example.accountManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5AXW0RUDHkRmlCY59K9-5XxRzLkGbLvE',
    appId: '1:45830351220:ios:098d8d63cf2353b150e421',
    messagingSenderId: '45830351220',
    projectId: 'account-management-4ce5a',
    storageBucket: 'account-management-4ce5a.firebasestorage.app',
    iosBundleId: 'com.example.accountManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfJPc7SV-RPdJ8MzY2q3-cqYy6ivSaTs',
    appId: '1:45830351220:web:9a95c2e10b81915350e421',
    messagingSenderId: '45830351220',
    projectId: 'account-management-4ce5a',
    authDomain: 'account-management-4ce5a.firebaseapp.com',
    storageBucket: 'account-management-4ce5a.firebasestorage.app',
    measurementId: 'G-FC0PEN2RFP',
  );
}
